#ifndef LIFEMOTIF_CONFIG_H
#define LIFEMOTIF_CONFIG_H

#define LIFEMOTIF_VERSION_MAJOR 0
#define LIFEMOTIF_VERSION_MINOR 1

#define LIFEMOTIF_ORGANIZATION "changwoo"
#define LIFEMOTIF_APPLICATION "lifemotif-desktop"

#endif // LIFEMOTIF_CONFIG_H
